import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import './styles/styles.css'
import Navbar from "@/components/Navbar";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <main className="max-w-[100%]">
        <Navbar />
        {children}
        </main>
      </body>
    </html>
  );
}
